/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The full goal category definition.
 */
export interface Category {
  id: string;
  name: string;
  gameId: string;
  max: number;
}
