/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Board = RevealedBoard | HiddenBoard;
export type Cell = RevealedCell | HiddenCell;

export interface RevealedBoard {
  board: Cell[][];
  hidden?: false;
  width: number;
  height: number;
}
export interface RevealedCell {
  goal: Goal;
  completedPlayers: string[];
  revealed: true;
}
/**
 * A single objective for a bingo game.
 */
export interface Goal {
  id: string;
  goal: string;
  description: string | null;
  difficulty?: number | null;
  categories?: Category[];
  image?: GoalImage;
  secondaryImage?: GoalImage;
  imageTag?: GoalImageTag;
  count?: number;
}
/**
 * The full goal category definition.
 */
export interface Category {
  id: string;
  name: string;
  gameId: string;
  max: number;
}
export interface GoalImage {
  id: string;
  name: string;
  mediaFile: string;
}
export interface GoalImageTag {
  id: string;
  label: string;
  color: string;
}
export interface HiddenCell {
  revealed: false;
  completedPlayers: string[];
}
export interface HiddenBoard {
  hidden: true;
  width: number;
  height: number;
}
