/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Board = RevealedBoard | HiddenBoard;
export type Cell = RevealedCell | HiddenCell;

export interface RevealedBoard {
  board: Cell[][];
  hidden?: false;
  width: number;
  height: number;
}
export interface RevealedCell {
  goal: Goal;
  completedPlayers: string[];
  revealed: true;
}
/**
 * A single objective for a bingo game.
 */
export interface Goal {
  id: string;
  goal: string;
  description: string | null;
  /**
   * Translation texts for this goal in json object
   */
  translations: {
    [k: string]: string;
  };
  difficulty?: number | null;
  categories?: string[];
}
export interface HiddenCell {
  revealed: false;
  completedPlayers: string[];
}
export interface HiddenBoard {
  hidden: true;
  width: number;
  height: number;
}
