/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Cell = RevealedCell | HiddenCell;

export interface RevealedCell {
  goal: Goal;
  completedPlayers: string[];
  revealed: true;
}
/**
 * A single objective for a bingo game.
 */
export interface Goal {
  id: string;
  goal: string;
  description: string | null;
  difficulty?: number | null;
  categories?: Category[];
  tags?: GoalTag[];
}
/**
 * The full goal category definition.
 */
export interface Category {
  id: string;
  name: string;
  gameId: string;
  max: number;
}
/**
 * A grouper for goals, used during some board generation mechanics.
 */
export interface GoalTag {
  id: string;
  name: string;
  goalCount?: number;
}
export interface HiddenCell {
  revealed: false;
  completedPlayers: string[];
}
