/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Game {
  id: string;
  name: string;
  slug: string;
  coverImage?: string;
  owners?: User[];
  moderators?: User[];
  favorited?: boolean;
  isMod?: boolean;
  enableSRLv5?: boolean;
  racetimeBeta?: boolean;
  racetimeCategory?: string;
  racetimeGoal?: string;
  difficultyVariantsEnabled?: boolean;
  difficultyVariants?: DifficultyVariant[];
  difficultyGroups?: number;
  slugWords?: string[];
  useTypedRandom?: boolean;
  generationSettings?: {
    [k: string]: unknown;
  };
  newGeneratorBeta?: boolean;
  descriptionMd?: string;
  setupMd?: string;
  linksMd?: string;
  variants?: Variant[];
  images?: GoalImage[];
  imageTags?: GoalImageTag[];
}
export interface User {
  id: string;
  username: string;
  email?: string;
  staff: boolean;
  racetimeConnected?: boolean;
  avatar?: string;
}
export interface DifficultyVariant {
  id?: string;
  name: string;
  goalAmounts?: number[];
}
export interface Variant {
  id: string;
  name: string;
  description?: string;
  generatorSettings?: {
    [k: string]: unknown;
  };
}
export interface GoalImage {
  id: string;
  name: string;
  mediaFile: string;
}
export interface GoalImageTag {
  id: string;
  label: string;
  color: string;
}
