/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The available generation options for a game
 */
export interface GeneratorOptions {
  steps: GeneratorStep[];
}
/**
 * The generation steps that configuration is available for
 */
export interface GeneratorStep {
  /**
   * The name of the generation step
   */
  displayName: string;
  /**
   * The internal value for this rule
   */
  value: string;
  /**
   * Help text for the step, which explains what what the step does in the overall generation process
   */
  description: string;
  /**
   * The list of valid rule values for this step
   */
  availableRules: StepRule[];
  /**
   * If this step allows multiple rules to be selected
   */
  selectMultiple: boolean;
  /**
   * If a value for this step is required in order for generation to function. If a value is not required, an empty aarray will be allowed for multiple response rules.
   */
  required: boolean;
}
export interface StepRule {
  /**
   * User friendly display name of this rule
   */
  displayName: string;
  /**
   * The internal database enum value for this rule
   */
  value: string;
  /**
   * Help text for the rule, which explains what how the rule impacts generation
   */
  description: string;
}
