/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A grouper for goals, used during some board generation mechanics.
 */
export interface GoalTag {
  id: string;
  name: string;
  goalCount?: number;
}
