/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Player {
  id: string;
  nickname: string;
  color: string;
  goalCount: number;
  raceStatus: RaceStatusDisconnected | RaceStatusConnected;
  spectator: boolean;
  monitor: boolean;
  showInRoom: boolean;
}
export interface RaceStatusDisconnected {
  connected: false;
}
export interface RaceStatusConnected {
  connected: true;
  /**
   * Username connected to this player for the race, if it is separate from PlayBingo
   */
  username: string;
  ready?: boolean;
  /**
   * Race finish time (ISO 8601 duration)
   */
  finishTime?: string;
}
