FROM node:20

WORKDIR /web

COPY tsconfig.json package.json package-lock.json ./
COPY ./public ./public
COPY .eslintrc.json .prettierignore next.config.js ./

RUN npm i

COPY ./src ./src

CMD [ "npm", "run", "dev" ]